name: 'ghettohubDB'
description: 'A database driver for a JSON DB in a GitHub repo'
author: 'Josh Wulf <josh@magikcraft.io>'
inputs:
  github_token: 
    required: true
    description: "Set to $${{ secrets.GITHUB_TOKEN }} so the database can commit to the repo"
  operation:    
    required: true         
    description: 'The operation to perform: FIND | UPSERT | DELETE | INIT'
  query: 
    required: false
    description: "The query to execute"
  record:
    required: false
    description: "The record for an upsert operation"
  table:
    required: false
    description: "The table to run the operation on"
  basedir:
    required: false
    description: "The base directory for the database"
    default: "db"
runs:
  using: 'node12'
  main: 'dist/index.js'
