name: 'ghettohubDB'
description: 'A database driver for a JSON DB in a GitHub repo'
author: 'Josh Wulf <josh@magikcraft.io>'
inputs:
  github_token: 
    required: true
    description: "A GitHub token to commit to the repo. Pass in secrets.GITHUB_TOKEN."
  operation:    
    required: true         
    description: 'The operation to perform: FINDONE | FINDMANY | DROPTABLE | UPSERT | DELETEONE | DELETEMANY | INIT | UPDATEONE | UPDATEMANY'
  query: 
    required: false
    description: "The query to execute"
  record:
    required: false
    description: "The record for an upsert operation"
  table:
    required: false
    description: "The table to run the operation on"
  basedir:
    required: false
    description: "The base directory for the database"
    default: "db"
  tables:
    required: false
    description: "A list of tablenames to initialise a database"
runs:
  using: 'node12'
  main: 'dist/index.js'
